import { ComboBox, Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct Autonomous {
    color: string,
    index: int,
    side: string,
}

export component AppWindow inherits Window {
    width: 480px;
    height: 240px;

    callback autonomous(Autonomous);
    callback test();

    callback request-path();
    in-out property<image> path_image <=> path.source;
    
    HorizontalLayout {
        spacing: 140px;

        VerticalLayout {
            spacing: 10px;
            padding: 10px;
            width: 100px;

            HorizontalLayout {
                spacing: 5px;
                height: 40px;

                mode_cb := ComboBox {
                    width: 160px;
                    
                    model: [
                        "Select Auton",
                        "Left",
                        "Left (mess up)",
                        "Right",
                        "Skills",
                    ];
                }

                color_cb := Button {
                    width: 60px;
                    checkable: true;
                    text: self.checked ? @tr("blue") : @tr("red");
                }
            }

            Button {
                text: "save";
                height: 40px;
                width: 225px;
                clicked => {
                    root.autonomous({
                        color: color_cb.text,
                        index: mode_cb.current_index,
                        side: mode_cb.current_value,
                    });
                    root.request-path();
                }
            }

            Button {
                text: "run";
                height: 40px;
                width: 225px;
                clicked => {
                    root.test();
                }
            }
        }
        
        Rectangle {
            width: 240px;
            height: 240px;
            
            Image {
                source: @image-url("../images/TopView.svg");
                width: 100%;
                height: 100%;
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            path := Image {
                width: parent.width;
                height: parent.height;
            }
        }
    }
}

